---
name: 'package'
on:
  push:
    branches:
      - master
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: "refs/tags/v(.*)"
      - name: 'checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: patch
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: master
          WITH_V: true
      - name: 'version'
        run: make version
